### ISSUE TITLE
Online demo issue

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_web_emscripten#11]
I was trying to update the widgets demo to v8 on https://lvgl.io/demos.

I've simply built it with CMake but the demo is not loaded. There is no obvious error in the console. 

@embeddedt  so you see what could be the problem?

**Comment by embeddedt** [comment]
It looks like [`lvgl_shell.html`](https://github.com/lvgl/lv_sim_emscripten/blob/master/lvgl_shell.html) was not used in your version, as the custom scripts and styles are missing. That's weird, as it is [explicitly requested](https://github.com/lvgl/lv_sim_emscripten/blob/46628050d2074acbcb2e20a9ba48a4565013058d/CMakeLists.txt#L21) in the CMakeLists file. The script is needed in order for the screen width and height to be chosen correctly.

I just tried a local build and it seems to have worked for me (Emscripten 2.0.4, CMake 3.20.2). The build on GitHub [also works fine](https://lvgl.github.io/lv_sim_emscripten/).

**Comment by kisvegabor** [comment]
Thanks! I've used the previous HTML file because I thought only the JS and WASM files matter.

Now it works well with the new HTML file.
