### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by garudaonekh** [lvgl/lv_web_emscripten#21]
Hi,
At the last step of the build (**emmake make -j4**), I got the following error.

I use MacOS Ventura 13.5

```
main.c:114:5: error: unknown type name 'lv_display_t'; did you mean 'lv_disp_t'?
  114 |     lv_display_t * disp = lv_sdl_window_create(monitor_hor_res, monitor_ver_res);
      |     ^~~~~~~~~~~~
      |     lv_disp_t
/Users/xxx/emsdk/lv_web_emscripten/lvgl/src/core/../core/lv_disp.h:37:27: note: 'lv_disp_t' declared here
   37 | typedef struct _lv_disp_t lv_disp_t;

```

It looks like the submodule points to the old version of lvgl. Any suggestion to update this?

Thanks;

**Comment by kisvegabor** [comment]
I've just update the submodule. 

You can also just pull latest lvgl from master.

**Comment by garudaonekh** [comment]
It works. 
Thanks;
