### ISSUE TITLE
Compile failed!

### ISSUE THREAD

**Issue by lilengqiang** [lvgl/lv_web_emscripten#6]
![图片](https://user-images.githubusercontent.com/52372001/86313192-1d6bc480-bc57-11ea-8ac7-deac56cd5926.png)

**Comment by embeddedt** [comment]
It works for me using the latest version of Emscripten. What version of it are you using? Are you using the latest version of this repository from `master`, with submodules updated (`git submodule update --init --recursive`)?

Please try a clean build (`make clean`) with a fresh copy of [the latest version of Emscripten](https://emscripten.org/docs/getting_started/downloads.html#download-and-install) and see if the problem persists.

**Comment by kisvegabor** [comment]
Have you installed SDL? What is the output for `sdl2-config`?

**Comment by embeddedt** [comment]
@kisvegabor I'm pretty sure having SDL installed on the host doesn't affect Emscripten (since it uses its own version), but it's worth a try.

**Comment by lilengqiang** [comment]
sudo apt-get install libsdl2-dev

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/86465942-3f536d00-bd65-11ea-9da0-eb4be9ba31ee.png)
@kisvegabor @embeddedt  what's the problem?

**Comment by kisvegabor** [comment]
These are present on https://lvgl.io/demos too but it's still working

**Comment by incity** [comment]
yes i know, but i want to compile one on my localhost, and came out this problem.

**Comment by embeddedt** [comment]
Try running it so that `lvgl.html` is in the root folder (i.e.. serve the `emscripten` folder as the HTML root directory).

**Comment by embeddedt** [comment]
The streaming error shouldn't break the webpage; it's just letting you know that the site will fall back to a different way of downloading the WASM.

**Comment by incity** [comment]
@embeddedt Yes, that's what I did

**Comment by incity** [comment]
how can i correct it?

**Comment by kisvegabor** [comment]
Please try in Firefox without a webserver. Pay attention to this: https://github.com/lvgl/lv_sim_emscripten#known-issue-with-firefox

**Comment by incity** [comment]
yes, i did it, but it failed(same error reason), so i put it to the web server.

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/86467336-cefa1b00-bd67-11ea-9bdd-40ad9da7bb3d.png)

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/86467664-5d6e9c80-bd68-11ea-89b8-9abb0e1ce03d.png)
