### ISSUE TITLE
Build "normal" website

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_web_emscripten#8]
I've tried to build a normal website with the project in the `master` branch but seemingly it's adjuted to create websites for the examples.

@embeddedt Is there a config option for the old behavior?

**Comment by embeddedt** [comment]
Sorry; I'm not sure exactly what you mean by old behavior. Could you explain, please?

You can pass `CHOSEN_DEMO=<any example/demo>` to choose which example you want. I believe the previous version was hardcoded to `lv_demo_widgets` (which is still the default).

**Comment by kisvegabor** [comment]
For the music demo I got this html:
![image](https://user-images.githubusercontent.com/7599318/101163816-7be90480-3634-11eb-9007-a4f90c277adb.png)

After taking a second look  I noticed that the extra git related lines can be removed by using another template HTML.

By "normal" behavior I meant to just get a clean index.html from any custom code (not necessarily built-in demos).

**Comment by embeddedt** [comment]
Now I understand.

You can pass `NO_GIT_HASH=1` to the Makefile to remove the Git commit information.

For the custom code, you can just edit `main.c` and remove the `CHOSEN_DEMO()` call; that just replaced the hardcoded one that was there previously.

**Comment by kisvegabor** [comment]
I see, thank you.

> You can pass NO_GIT_HASH=1 to the Makefile to remove the Git commit information.

I think `ADD_GIT_HASH = 1` would make more sense but probably it's not worth to effort to change it. Anyway, could you add a few lines about these options in the README?

**Comment by embeddedt** [comment]
Added. https://github.com/lvgl/lv_sim_emscripten/blob/master/README.md#build-options-environment-variables

**Comment by kisvegabor** [comment]
Thanks, I've just added a short example too.
