### ISSUE TITLE
Which code should I recompose if I want to make changes in build/index.js

### ISSUE THREAD

**Issue by sk123sos** [lvgl/lv_web_emscripten#9]
I want to add a timestamp into the created build/index.js,can I recompose some code to add time stamp into it?

**Comment by embeddedt** [comment]
This is somewhat off-topic since it doesn't pertain to anything LVGL-specific, but I would piggyback on [this line of the Makefile](https://github.com/lvgl/lv_sim_emscripten/blob/15c5f596859b509ea96e250411deea9cffbc7ed1/Makefile#L56) and prepend something like `window.buildTimestamp = \"$(shell date)\";` to the echo string.

**Comment by sk123sos** [comment]
> This is somewhat off-topic since it doesn't pertain to anything LVGL-specific, but I would piggyback on [this line of the Makefile](https://github.com/lvgl/lv_sim_emscripten/blob/15c5f596859b509ea96e250411deea9cffbc7ed1/Makefile#L56) and prepend something like `window.buildTimestamp = \"$(shell date)\";` to the echo string.

thanks for help，I have a new qusetion now,If I change the limited size to 1920*1080,I will get lots of mem error,what should I do to avoid this?

**Comment by embeddedt** [comment]
Are you referring to the screen resolution? You would need to increase the maximum allowed size in [`lv_conf.h`](https://github.com/lvgl/lv_sim_emscripten/blob/15c5f596859b509ea96e250411deea9cffbc7ed1/lv_conf.h#L23-L24).

**Comment by sk123sos** [comment]
> Are you referring to the screen resolution? You would need to increase the maximum allowed size in [`lv_conf.h`](https://github.com/lvgl/lv_sim_emscripten/blob/15c5f596859b509ea96e250411deea9cffbc7ed1/lv_conf.h#L23-L24).

yes I did ,but it shows that 
LINK  build/index.html
wasm-ld: error: initial memory too small, 22014176 bytes needed
emcc: error: failed (1)
Makefile:52: recipe for target 'build/index.html' failed

**Comment by embeddedt** [comment]
What values did you increase it to? It's asking for 20GB of RAM! :confused:

**Comment by sk123sos** [comment]
> What values did you increase it to? It's asking for 20GB of RAM! 😕

I only change the lv_conf.h with
#define LV_HOR_RES_MAX 1920
#define LV_VER_RES_MAX 1080

**Comment by embeddedt** [comment]
I did the calculation wrong; it's actually only asking for 20MB, which is much more reasonable. Try adding `-s INITIAL_MEMORY=67108864` beside the other `-s` argument on lines 49 and 53.

**Comment by sk123sos** [comment]
> I did the calculation wrong; it's actually only asking for 20MB, which is much more reasonable. Try adding `-s INITIAL_MEMORY=67108864` beside the other `-s` argument on lines 49 and 53.

Thanks for help,I will try it later
